### ISSUE TITLE
下面的tableview 改成  UITableViewStyleGrouped，区头不悬停了，我刷新用MJRefresh库，怎么实现啊？

### ISSUE THREAD

**Issue by zengjinzong** [H2OB/FFPage#1]

**Comment by H2OB** [comment]
1.UITableViewStyleGrouped 方式的tableView 不支持悬停区头
2.刷新控件是单独针对本组件的，核心思想和MJRefresh差不多，你可以个性化定制
参考RefreshView

  @interface RefreshView ()

@property (retain ,nonatomic) UIActivityIndicatorView * indicatorView;

@end

@implementation RefreshView

/**
 设置子视图
 */
- (void)setUpSubView{
    
    self.indicatorView = [[UIActivityIndicatorView alloc]initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];
    self.indicatorView.hidesWhenStopped =NO;
    [self addSubview:self.indicatorView];
}

/**
 状态改变
 */
- (void)statusUpdated{
    
    if (self.status == FFRereshStatusNormal){
        
        [self.indicatorView stopAnimating];
        
        return;
    }
    
    if (self.status == FFRereshStatusRereshing){
        
       [self.indicatorView startAnimating];
        
        return;
    }
    
}

/**
 上拉下拉百分比改变
 */
- (void)percentUpdated{
    
    
}
//子视图布局
- (void)layoutSubviews{
    
    self.indicatorView.center = CGPointMake(CGRectGetWidth(self.bounds)/2.0, CGRectGetHeight(self.bounds)/2.0);
}

**Comment by current-User-ID** [comment]
第一个加载出来的页面不支持悬停,切换到下一个就可以了,在切换回来第一个也可以了,不知道为什么就第一次刚进页面的时候,第一个加载出来的页面不能悬停

**Comment by H2OB** [comment]
贴一下你代码 最大的可能是没有调用 
```
[self.mainController updateCurrentController:pageViewController.currentController];
```

**Comment by H2OB** [comment]
不是bug
