### ISSUE TITLE
在swift中 有个问题 ，tableView分组拖拽滑动后， 要点两次cell 才走didSelected方法

### ISSUE THREAD

**Issue by liubiaocong** [H2OB/FFPage#2]

**Comment by H2OB** [comment]
这个跟语言没有关系,下上滚动的时候系统的滚动被禁用的，然后用物理引擎模仿的滚动来解决手势冲突，如果物理行为没有结束滚动视图的交互是被关闭的，但是滚动视图有一个特点，滚动中如果你单点，他会马上停止下来，所以可能会出现你说的那种情况，算个瑕疵吧，目前正在想办法解决这个问题

**Comment by liubiaocong** [comment]
不是滚动中单点，是停止后了点击要点击多次，你可以在didSelected 里面打个print ，并没有走。。

**Comment by H2OB** [comment]
如果tableView在headViewController 里面，这个是苹果的bug，当scrollEnable = NO，或者 bounces = NO,可能会点击两次才响应
如果是在底部的tableView 已经修复

**Comment by liubiaocong** [comment]
好的，原来是点击两次什么原因导致的呢
