### ISSUE TITLE
使用感受

### ISSUE THREAD

**Issue by FaDeve** [H2OB/FFPage#4]
首先很感谢作者开源这个框架，看了下源码实现，里面的控制器缓存实现思路和物理模拟滚动很好，对使用者也很友好，代理清晰。不过使用过程中，有几个地方不是很明，还望作者指点。
1.对于pageViewController，如果业务需要展现不同种类的控制器，可以在- (UIViewController *)pageViewController:(FFPageViewController *)pageViewConteoller controllerForPage:(NSInteger)page 根据 page 设置不同的控制器，那self.homePageViewController.tabViewController 这里该如何设置呢？
2.希望可以在 FFPageViewControllerDelegate 提供 scrollerView偏移量回调代理，例如对导航栏或是 headerView 做额外设置
3.希望可以回调 下方控制器 即将进入，已经进入，即将消失，已经消失等代理，若业务方需要对下方控制器进行埋点统计，将会很好处理
4.看框架里有FFRereshView,可以自定义很好。不过希望可以提供外界配置的代理（如可以继续使用 MJRefresh），就像灵活配置tabViewController那样。
以上几点，就是使用过程发现的问题，望作者采纳，谢谢~

**Comment by H2OB** [comment]
FFHomePageViewController 的作用仅仅是一个组装工厂和手势冲突的解决者，它不涉及到你里面显示什么，也不影响你出传入的控制器， 你传给他相关高度和相关控制器，它就把你传入的控制器用合适的大小放在合适的位置，以及解决手势冲突，tabViewController  他只是一个控制器，你可以各种自定义,前提是你是一个控制器，本项目中的tabViewController 就仅仅是一个分类视图放在一个控制器里面而已，他其实也支持各种自定义，因为好的第三方分类视图太多，例如本项目中使用SPPageMenu（https://github.com/SPStore/SPPageMenu） 以及另一个JXCategoryView (https://github.com/pujiaxin33/JXCategoryView) 都非常不错，所以就没造轮子。这使用控制器而不使用view的目的是解耦。

FFPageViewControllerDelegate的scrollview 偏移量问题，可以采用KVO的方式来监听偏移量,关于滑动代理可以加上

希望可以回调 下方控制器 即将进入，已经进入，即将消失，已经消失等代理，FFPageViewController 其实已经做了处理，子控制器的生命周期管理已经做好了，你只需要在子控制器里面实现系统的即将进入，已经进入，即将消失，已经消失等代理 详见左右滚动过程中控制台日志打印

关于MJRefresh, 因为原理都是一样，但是MJRefresh能够刷新的原因是scrollview.isDraging = YES，而FFHomePageViewController 是把滚动事件禁用的，用物理引擎模拟滚动的，所以就不兼容了

**Comment by H2OB** [comment]
另外，FFHomePageViewController 所接受传入的3个控制器 headViewController,pageViewController,tabViewController 都完全可以自定义 

再另外，最近几个月在忙结婚的事情，不好意思才回复
