### ISSUE TITLE
切换选项卡 header停留顶部不滑动的情况 

### ISSUE THREAD

**Issue by luyouxing** [H2OB/FFPage#5]
#pragma mark -  内外部滚动视图的偏移量处理
- (void)transitionWithOffset:(CGFloat)offset{
    
    CGFloat outOffY = self.scrollview.contentOffset.y;//外部滚动视图的偏移量
    CGFloat subOffY = [self.controller scrollview].contentOffset.y; //子视图的偏移量
    CGFloat maxOffY = self.headHeight - self.ignoreTopSpeace + self.scrollview.contentInset.top;//headView悬浮的时候最大偏移量
    CGFloat maxSubOffY = [self.controller scrollview].maxOffsetY;
        
    //手指向上
    if(offset < 0){
         //修改处 开始
        //处理 切换选项卡 header停留顶部不滑动的情况
        if(outOffY < maxOffY){
            CGFloat final = outOffY - offset - maxOffY;
            if(final < 0){
                outOffY -= offset;
                [self setOutScrollViewOffY:outOffY];
            }else{
                outOffY = maxOffY;
                [self setOutScrollViewOffY:outOffY];
                [self transitionWithOffset:-final];
            }
        }
        //修改处 结束
        // *********优先判断子视图是否滚动到顶部
        //子视图未滚动到顶部
        if(subOffY > 0){

**Comment by H2OB** [comment]
切换选项卡向上滚动head不跟着滚动，是因为下方滚动视图偏移量已经大于0了，这里可以在下方pageSubViewController的视图控制器将要出现的时候设置他的滚动视图偏移量为0就可以解决
